package com.utime.memoBom.common.schemasync;

import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public record ColumnSpec(
        String name,
        String rawType,          // e.g. VARCHAR(128), BIGINT, TIMESTAMP, UUID, CHAR(2), BOOLEAN
        boolean notNull,
        String defaultExpr,      // e.g. CURRENT_TIMESTAMP, FALSE, 'MD', RANDOM_UUID()
        boolean identity         // "GENERATED BY DEFAULT AS IDENTITY" 포함 여부
) {
    private static final Pattern FIRST_WORD = Pattern.compile("^\\s*([A-Za-z0-9_]+)\\s+(.*)$");

    public static ColumnSpec parse(String columnDef) {
        // 예: USER_NO BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        // 예: REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
        // 예: FONT_SIZE CHAR(2) DEFAULT 'MD'
        Matcher m = FIRST_WORD.matcher(columnDef.trim());
        if (!m.find()) throw new IllegalArgumentException("Invalid column def: " + columnDef);

        String name = m.group(1).toUpperCase(Locale.ROOT);
        String rest = m.group(2).trim();

        boolean identity = rest.toUpperCase(Locale.ROOT).contains("GENERATED BY DEFAULT AS IDENTITY");

        // 타입은 "첫 토큰(+괄호)" 정도로 잡는다: VARCHAR(128), CHAR(2), BIGINT, TIMESTAMP...
        String type = extractType(rest);

        boolean notNull = rest.toUpperCase(Locale.ROOT).contains("NOT NULL");

        String defaultExpr = extractDefault(rest);

        return new ColumnSpec(name, type.toUpperCase(Locale.ROOT), notNull, defaultExpr, identity);
    }

    private static String extractType(String rest) {
        // rest의 맨 앞에서 타입 토큰(괄호 포함)을 추출
        // 예: "VARCHAR(128) DEFAULT NULL" -> "VARCHAR(128)"
        // 예: "BIGINT GENERATED BY DEFAULT AS IDENTITY" -> "BIGINT"
        String r = rest.trim();

        // 첫 공백 전까지 보되, 괄호가 열리면 닫힐 때까지 포함
        StringBuilder sb = new StringBuilder();
        int depth = 0;
        for (int i = 0; i < r.length(); i++) {
            char ch = r.charAt(i);
            if (ch == ' ' && depth == 0) break;
            if (ch == '(') depth++;
            if (ch == ')') depth--;
            sb.append(ch);
        }
        return sb.toString().trim();
    }

    private static String extractDefault(String rest) {
        String upper = rest.toUpperCase(Locale.ROOT);
        int idx = upper.indexOf("DEFAULT ");
        if (idx < 0) return null;

        String after = rest.substring(idx + "DEFAULT ".length()).trim();

        // DEFAULT 다음이 "NULL" 이면 defaultExpr는 null 취급(의미없음)
        if (after.toUpperCase(Locale.ROOT).startsWith("NULL")) return null;

        // DEFAULT 표현식은 다음 키워드(NOT NULL/PRIMARY KEY/CONSTRAINT/UNIQUE/...) 전까지
        String[] stopWords = {" NOT NULL", " PRIMARY KEY", " UNIQUE", " CONSTRAINT", " GENERATED", " REFERENCES"};
        int cut = after.length();
        String upperAfter = after.toUpperCase(Locale.ROOT);

        for (String sw : stopWords) {
            int p = upperAfter.indexOf(sw);
            if (p >= 0) cut = Math.min(cut, p);
        }
        return after.substring(0, cut).trim();
    }
}
